# Generated by Django 3.2.12 on 2024-04-07 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantplan',
            name='equipo',
        ),
    ]
