# Generated by Django 3.2.12 on 2024-04-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_remove_mantplan_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantplan',
            name='codigo',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
