# Generated by Django 3.2.12 on 2024-04-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_mantplan_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantplan',
            name='abrilP',
            field=models.CharField(default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='abrilR',
            field=models.CharField(default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='agostoP',
            field=models.CharField(default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='agostoR',
            field=models.CharField(default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='diciembreP',
            field=models.CharField(default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='diciembreR',
            field=models.CharField(default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='eneroP',
            field=models.CharField(default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='eneroR',
            field=models.CharField(default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='febreroP',
            field=models.CharField(default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='febreroR',
            field=models.CharField(default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='julioP',
            field=models.CharField(default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='julioR',
            field=models.CharField(default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='junioP',
            field=models.CharField(default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='junioR',
            field=models.CharField(default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='marzoP',
            field=models.CharField(default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='marzoR',
            field=models.CharField(default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='mayoP',
            field=models.CharField(default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='mayoR',
            field=models.CharField(default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='noviembreP',
            field=models.CharField(default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='noviembreR',
            field=models.CharField(default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='octubreP',
            field=models.CharField(default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='octubreR',
            field=models.CharField(default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='septiembreP',
            field=models.CharField(default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='septiembreR',
            field=models.CharField(default='No', max_length=2),
        ),
    ]
