# Generated by Django 3.2.12 on 2024-04-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_auto_20240408_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantplan',
            name='abrilR',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='agostoR',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='diciembreR',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='eneroR',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='febreroR',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='julioR',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='junioR',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='marzoR',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='mayoR',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='noviembreR',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='octubreR',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mantplan',
            name='septiembreR',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
