# Generated by Django 3.2.12 on 2024-03-07 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=100)),
                ('unidad', models.CharField(max_length=5)),
                ('cantidad', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novale', models.CharField(max_length=5)),
                ('idprod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producciones.producciones')),
            ],
        ),
    ]
