# Generated by Django 3.2.12 on 2024-03-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiales',
            name='almacen',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiales',
            name='costo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiales',
            name='entregado',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
