# Generated by Django 3.2.12 on 2024-03-11 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producciones', '0002_auto_20240311_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiales',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
