# Generated by Django 3.2.12 on 2024-03-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producciones', '0004_remove_materiales_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiales',
            name='fecha',
            field=models.DateField(default='2024-03-10'),
            preserve_default=False,
        ),
    ]
