# Generated by Django 3.2.12 on 2024-07-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producciones', '0006_producciones_fechaf'),
    ]

    operations = [
        migrations.AddField(
            model_name='producciones',
            name='lote',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
