# Generated by Django 3.2.12 on 2024-07-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producciones', '0007_producciones_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='producciones',
            name='mes',
            field=models.CharField(default='enero', max_length=50),
            preserve_default=False,
        ),
    ]
