# Generated by Django 3.2.12 on 2024-01-21 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cosdigo', models.CharField(max_length=1)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codequipo', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=150)),
                ('masterArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codificadores.areas')),
            ],
        ),
    ]
