# Generated by Django 3.2.12 on 2024-01-21 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0002_areas_equipos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areas',
            old_name='cosdigo',
            new_name='codigo',
        ),
    ]
