# Generated by Django 3.2.12 on 2024-01-21 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0003_rename_cosdigo_areas_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipos',
            old_name='codequipo',
            new_name='codigo',
        ),
    ]
