# Generated by Django 3.2.12 on 2024-01-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0004_rename_codequipo_equipos_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='causas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
    ]
