# Generated by Django 3.2.12 on 2024-03-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0007_centrocosto_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajadores',
            name='solic',
            field=models.CharField(default='Solicita', max_length=8),
        ),
    ]
