# Generated by Django 3.2.12 on 2024-03-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0008_trabajadores_solic'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajadores',
            name='person',
            field=models.CharField(default='Mantenimiento', max_length=13),
        ),
    ]
