# Generated by Django 3.2.12 on 2024-02-04 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('almacen', models.CharField(max_length=50)),
                ('costo', models.CharField(max_length=50)),
                ('entregado', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='materalv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=150)),
                ('unida', models.CharField(max_length=4)),
                ('cantidad', models.FloatField()),
                ('vale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vales.vales')),
            ],
        ),
    ]
