# Generated by Django 3.2.12 on 2024-02-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vales', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='materalv',
            new_name='materialv',
        ),
    ]
