# Generated by Django 3.2.12 on 2024-02-04 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vales', '0002_rename_materalv_materialv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialv',
            old_name='unida',
            new_name='unidad',
        ),
    ]
