# Generated by Django 3.2.12 on 2024-02-04 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vales', '0003_rename_unida_materialv_unidad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vales',
            new_name='vale',
        ),
    ]
