# Generated by Django 3.2.12 on 2024-04-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vales', '0004_rename_vales_vale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialv',
            old_name='vale',
            new_name='valeID',
        ),
    ]
