# Generated by Django 3.2.12 on 2024-01-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=50)),
                ('equipo', models.CharField(max_length=150)),
                ('fechaRep', models.DateField()),
                ('prioridad', models.CharField(max_length=50)),
                ('fechaEje', models.DateField()),
                ('Resultado', models.TextField()),
                ('Destino', models.TextField(max_length=50)),
            ],
        ),
    ]
