# Generated by Django 3.2.12 on 2024-01-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='Destino',
            field=models.CharField(max_length=50),
        ),
    ]
