# Generated by Django 3.2.12 on 2024-02-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_alter_orden_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='valecodigo',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
