# Generated by Django 3.2.12 on 2024-02-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_orden_valecodigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='valecodigo',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
