# Generated by Django 3.2.12 on 2024-02-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_alter_orden_valecodigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='Resultado',
            new_name='Resumen',
        ),
        migrations.AddField(
            model_name='orden',
            name='Afectacion',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='Reparado',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='departamento',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='falla',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='idequipo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='motivosolic',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='solicitante',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orden',
            name='Destino',
            field=models.CharField(max_length=100),
        ),
    ]
