# Generated by Django 3.2.12 on 2024-02-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_auto_20240224_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='falla',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
