# Generated by Django 3.2.12 on 2024-02-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0006_alter_orden_falla'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='culminada',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orden',
            name='idequipo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='motivosolic',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
