# Generated by Django 3.2.12 on 2024-02-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0007_auto_20240225_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='culminada',
            field=models.CharField(max_length=2),
        ),
    ]
