# Generated by Django 3.2.12 on 2024-03-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0008_alter_orden_culminada'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='campa',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
