# Generated by Django 3.2.12 on 2024-06-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiempoperdido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiempo',
            name='tiempo',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
