# Generated by Django 3.2.12 on 2024-06-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiempoperdido', '0002_tiempo_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiempo',
            name='causa',
            field=models.CharField(max_length=150),
        ),
    ]
