# Generated by Django 3.2.12 on 2024-06-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiempoperdido', '0003_alter_tiempo_causa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiempo',
            old_name='tiempo',
            new_name='tiemp',
        ),
    ]
