# Generated by Django 3.2.12 on 2024-06-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiempoperdido', '0004_rename_tiempo_tiempo_tiemp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiempo',
            old_name='tiemp',
            new_name='dias',
        ),
    ]
